[package]
name = "cargo-ui"
version = "0.3.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-only"
description = "GUI for cargo"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "ui", "gui"]
repository = "https://github.com/sixtyfpsui/cargo-ui"
resolver = "2"

[features]
slint-backend-gl = ["slint/backend-gl"]
slint-backend-qt = ["slint/backend-qt"]
wayland = ["slint/wayland"]
x11 = ["slint/x11"]

default = ["x11", "wayland", "slint-backend-qt", "slint-backend-gl"]

[dependencies]
anyhow = "1"
cargo_metadata = "0.14"
crates-index = { version = "0.18.0" }
dunce = "1"
futures = "0.3"
itertools = "0.10"
open = "2"
rfd = { version = "0.7", default-features = false, features = [ "parent" ] }
serde = "1"
serde_json = "1"
shlex = "1"
slint = { version = "0.2.0", default-features = false, features = [ "compat-0-2-0" ] }
tokio = { version = "1.12.0", features= ["full"] }
toml_edit = "0.6.0"

[build-dependencies]
slint-build = { version = "0.2.0" }
